### ISSUE TITLE
Wrong transliteration of Bindu in Devanagari

### ISSUE THREAD

**Issue by SushantSDevlekar** [Tejesh-Raut/Devanagari-to-Brahmi-script#1]
Your converter is best otherwise, but I have encountered a minor problem. When I provide a Devanagari text, which contains Shirobindu, it does not get converted properly. 

Eg. If you give a input like बिंदू, the output will be 𑀩𑀺ं𑀤𑀽. Here the < ं > character it takes from Devanagari set of Unicode characters. The code is 0902. It should be Brahmi < 𑀁 > instead. The code is 11001.
	𑀩𑀺ं𑀤𑀽
	𑀩𑀺𑀁𑀤𑀽

Please do the needful to correct it. 
PLEASE SEE THE ATTACHMENT.

[brahmi_MWE.pdf](https://github.com/Tejesh-Raut/Devanagari-to-Brahmi-script/files/6170613/brahmi_MWE.pdf)

**Comment by Tejesh-Raut** [comment]
@SushantSDevlekar, thanks for notifying. I have updated it.

**Comment by bgo-eiu** [comment]
I am still having this issue with the application
