### ISSUE TITLE
Not able to type Brahmi script in word or excel

### ISSUE THREAD

**Issue by Mehul2205** [Tejesh-Raut/Devanagari-to-Brahmi-script#2]
I tried using the font provided on the website in excel and word and I don't see words getting translated to Brahmi Script.

# Excel
<img width="945" alt="image" src="https://user-images.githubusercontent.com/48055152/143281589-e5e879c9-92c2-484b-8bd2-641385ce716b.png">

# Word
<img width="744" alt="image" src="https://user-images.githubusercontent.com/48055152/143282428-c5deae7e-7f36-4028-97de-97046b144437.png">

If you have updated the fonts file then please mail that to this mail id - *mehulpatni.2205@gmail.com*

**Comment by Tejesh-Raut** [comment]
This webpage is designed for transliteration from Devanagari to Brahmi. You can't do the translation in word or excel. Copy it from website.

**Comment by Mehul2205** [comment]
I am saying that the font you provided - https://tejesh-raut.github.io/Devanagari-to-Brahmi-script/Fonts/NotoSansBrahmi-Regular.ttf is not working correctly. Using this font I should be able to write in the Brahmi language directly. So is there any option for that?
I know, I can go to the website and paste my content there and it will convert that into Brahmi. But that's a bit tedious task

**Comment by Tejesh-Raut** [comment]
This website was designed for that purpose only. That ttf font file alone cannot transliterate from Devanagari to Brahmi since the unicodes of Devanagari and Brahmi are different ranges. Please see the references for more details
